---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  wraaath:
    displayname: "Mads"
    password: $argon2id$v=19$m=65536,t=3,p=4$DQNECerTVRWRRtqopRhWhA$qna7rGvikfxkLlOwmjE6QJVDn99skzjPF88bjrt2ejk # replace with your own from the command in the README
    email: mads@wraaath.com
    groups:
      - admins
      - dev
...
