version: '3.9'
services:
  apache:
    image: httpd:alpine3.18
    restart: unless-stopped
    container_name: website
    networks:
    - proxy
    ports:
    - '80:80'
    volumes:
    - ./data:/usr/local/apache2/htdocs
    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
        - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
        - traefik.http.routers.vaultwarden-https.rule=Host(`wraaath.com`)
        - traefik.http.routers.vaultwarden-https.entrypoints=https
        - traefik.http.routers.vaultwarden-https.tls=true
        - traefik.http.routers.vaultwarden-https.service=vaultwarden
        - traefik.http.routers.vaultwarden-http.rule=Host(`wraaath.com`)
        - traefik.http.routers.vaultwarden-http.entrypoints=http
        - traefik.http.routers.vaultwarden-http.middlewares=redirect-https
        - traefik.http.routers.vaultwarden-http.service=vaultwarden
        - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    
networks:
  proxy:
    external: true